.PHONY: build

PROJECT_NAME = peer

build:
	docker-compose -p $(PROJECT_NAME) build

up:
	docker-compose -p $(PROJECT_NAME) up -d

stop:
	docker-compose -p $(PROJECT_NAME) stop

down:
	docker-compose -p $(PROJECT_NAME) down
